config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
  	root 'notes#index', as: "authenticated_root"
  end
  root 'welcome#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :find_note, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!
	
	def index
		@notes =Note.where(user_id: current_user)
	end

	def show
	end

	def new
		@note = current_user.notes.build
	end

	def create
		@note = current_user.notes.build(note_params)

			if @note.save
				redirect_to @note
			else 
				render 'new'
			end
	end

	def edit
	end

	def update
		if @note.update(note_params)
			redirect_to @note
		else 
			render 'edit'
		end
	end

	def destroy
		@note.destroy
		redirect_to notes_path
	end

	private
		def find_note
			@note = Note.find(params[:id])
		end

		def note_params
			params.require(:note).permit(:title, :content)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
 %title PowerNote | Online Notebook Application
 = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
 = javascript_include_tag 'application', 'data-turbolinks-track' => true
 %link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"}/
 = csrf_meta_tags
%body
 %header
  .header_inner
   = link_to image_tag( 'logo.png'), root_path, id: "logo"
   %nav
    - if user_signed_in?
     = link_to "New Note", new_note_path
     = link_to "Sign Out", destroy_user_session_path, method: :delete
    - else
     = link_to "Log In", new_user_session_path
 %p.notice= notice
 %p.alert= alert

 = yield
:javascript
  (function(i, s, o, g, r, a, m) {
   i['GoogleAnalyticsObject'] = r;
   i[r] = i[r] || function() {
    (i[r].q = i[r].q || []).push(arguments)
   }, i[r].l = 1 * new Date();
   a = s.createElement(o),
    m = s.getElementsByTagName(o)[0];
   a.async = 1;
   a.src = g;
   m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-75488487-1', 'auto');
  ga('send', 'pageview');

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
	= f.input :title
	= f.input :content
	= f.button :submit, class: "button"


:javascript
  (function(i, s, o, g, r, a, m) {
   i['GoogleAnalyticsObject'] = r;
   i[r] = i[r] || function() {
    (i[r].q = i[r].q || []).push(arguments)
   }, i[r].l = 1 * new Date();
   a = s.createElement(o),
    m = s.getElementsByTagName(o)[0];
   a.async = 1;
   a.src = g;
   m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-75488487-1', 'auto');
  ga('send', 'pageview');

app/views/notes/edit.html.haml
.wrapper_with_padding
	%h1 Edit Note

	= render 'form'

	= link_to "Cancel", note_path


:javascript
  (function(i, s, o, g, r, a, m) {
   i['GoogleAnalyticsObject'] = r;
   i[r] = i[r] || function() {
    (i[r].q = i[r].q || []).push(arguments)
   }, i[r].l = 1 * new Date();
   a = s.createElement(o),
    m = s.getElementsByTagName(o)[0];
   a.async = 1;
   a.src = g;
   m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-75488487-1', 'auto');
  ga('send', 'pageview');

app/views/notes/index.html.haml
.wrapper_with_padding
	#notes.clearfix
		- unless @notes.blank?
			- @notes.each do |note|
				%a{ href: (url_for [note])}
					.note
						%p.title= note.title
						%p.date= time_ago_in_words(note.created_at)
		- else
			%h2 Add a Note
			%p It appears you haven't created any notes yet... Lets fix that. Why don't you go ahead and create a new note.
			%button= link_to "New Note", new_note_path

:javascript
  (function(i, s, o, g, r, a, m) {
   i['GoogleAnalyticsObject'] = r;
   i[r] = i[r] || function() {
    (i[r].q = i[r].q || []).push(arguments)
   }, i[r].l = 1 * new Date();
   a = s.createElement(o),
    m = s.getElementsByTagName(o)[0];
   a.async = 1;
   a.src = g;
   m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-75488487-1', 'auto');
  ga('send', 'pageview');

app/views/notes/new.html.haml
.wrapper_with_padding
	%h1 Add A Note

	= render 'form'


:javascript
  (function(i, s, o, g, r, a, m) {
   i['GoogleAnalyticsObject'] = r;
   i[r] = i[r] || function() {
    (i[r].q = i[r].q || []).push(arguments)
   }, i[r].l = 1 * new Date();
   a = s.createElement(o),
    m = s.getElementsByTagName(o)[0];
   a.async = 1;
   a.src = g;
   m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-75488487-1', 'auto');
  ga('send', 'pageview');

app/views/notes/show.html.haml
.wrapper_with_padding
	#note_show
		%h1.title= @note.title
		%p= simple_format(@note.content)

		.buttons
			= link_to "Edit", edit_note_path(@note), class: "button"
			= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button"


:javascript
  (function(i, s, o, g, r, a, m) {
   i['GoogleAnalyticsObject'] = r;
   i[r] = i[r] || function() {
    (i[r].q = i[r].q || []).push(arguments)
   }, i[r].l = 1 * new Date();
   a = s.createElement(o),
    m = s.getElementsByTagName(o)[0];
   a.async = 1;
   a.src = g;
   m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-75488487-1', 'auto');
  ga('send', 'pageview');

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 PowerNote
		%p Your online notebook. Never forget an idea again.
		%button= link_to "Sign Up", new_user_registration_path
#testimonial
	.wrapper
		%p.quote "Your notebook as a web-app now"
		%p.name - Aditya Shukla
#callouts
	.callout_inner
		.wrapper
			.callout
			
				%h2 Notes
				%p You can write as much as you want in these notes.

			.callout
				%h2 Like
				%p You can write as much as you want in these notes.

			.callout
				%h2 Missile
				%p You can write as much as you want in these notes.
#bottom_cta
	.wrapper
		%p I want you to sign up... If you don’t. I will find you and I will kill you! - Liam Neeson
		%h2 Press It!
		%button= link_to "Click Here!", new_user_registration_path

%footer
	%p &copy; 2015 Aditya Shukla


:javascript
  (function(i, s, o, g, r, a, m) {
   i['GoogleAnalyticsObject'] = r;
   i[r] = i[r] || function() {
    (i[r].q = i[r].q || []).push(arguments)
   }, i[r].l = 1 * new Date();
   a = s.createElement(o),
    m = s.getElementsByTagName(o)[0];
   a.async = 1;
   a.src = g;
   m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-75488487-1', 'auto');
  ga('send', 'pageview');